spring:
  profiles:
    include: secret
  datasource:
    url: jdbc:h2:mem:boarddb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update  # 애플리케이션 실행 시 DB 스키마 자동 업데이트
    show-sql: true      # 쿼리 로그 출력
  h2:
    console:
      enabled: true
      path: /h2-console # 브라우저에서 localhost:8080/h2-console로 DB 확인 가능
server:
  port: 8080
